Kimmy/dpe more
HDFGroup/hermes pull request #45
Opened 2020-11-03 19:35 UTC by jya-kmu

Update DPE function and use library function in tests

2020-11-05 18:50 UTC, ChristopherHogan requested changes

2020-11-06 22:52 UTC, jya-kmu commented on src/data_placement_engine.cc
>                         std::vector<PlacementSchema> &output) {
Yes, we should do that.

2020-11-06 23:17 UTC, jya-kmu commented on src/data_placement_engine.cc
> +                       size_t blob_size, std::vector<PlacementSchema> &output) {
I will incorporate this fix.

2020-11-10 16:50 UTC, ChristopherHogan approved these changes
Very nice!

2020-11-10 21:01 UTC, merged